### PR TITLE
Patch for Home Assistant Core 2024.5

### PR DESCRIPTION
**Pull request by unze**
Patch for Home Assistant Core 2024.5
https://github.com/tolwi/hassio-ecoflow-cloud/issues/232

### CODE REVIEW

**Review by mfarad — APPROVED** [review]
Tested with HA 2024.5 --> OK !

**Review by mfarad — APPROVED** [review]
Tested with HA 2024.5 --> OK !

**Review by eagleco — APPROVED** [review]
Changes look good, just replaces instances of
`self.async_write_ha_state()`
with
`self.schedule_update_ha_state()`

Tested on my installation of HA 2024.5 and working fine again

**Comment by sparkyws** [comment]
Tested with...

Core 2024.5.1
Supervisor 2024.04.4
Operating System 12.2
Frontend 20240501.0.......Working Great

**Comment by rhyddereh** [comment]
Seems well enough tested, any chance at a merge?

**Comment by angelbarrera92** [comment]
> Seems well enough tested, any chance at a merge?

+1 here

**Comment by KarinBerg** [comment]
Works on Home Assistant Installation on Raspi 4 with:
Core 2024.5.2
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

**Comment by KarinBerg** [comment]
@unze Just wondering if we might need some if-else on the HA core version so that the integration is still working on older Home Assistant Core versions than 2024.5?

**Comment by unze** [comment]
i don't think we need that, as the function has been available since at least 2016
source: https://github.com/home-assistant/core/issues/4417

**Pull request merged**
