### PR TITLE
Addition of Smart Home Panel

### PR DESCRIPTION
**Pull request by Ne0-Hack3r**
These changes are based on the branch created by @tolwi 3 months ago but with the changes incorporated into the current main branch. I have tested against my own SHP running firmware version 6.0.0.25 on Home Assistant Core 2024.2.2 with Home Assistant OS 11.5

This includes all the main sensors but does not include power sensors that are derived from calculations of other sensors or cumulative energy sensors for use with the energy dashboard that source from the power sensors for individual circuits as highlighted on the image below.

image

We can discuss how best to incorporate both the circled energy sensors which are reported by the SHP itself as well as the calculated power and energy sensors in this integration.

Also: There is a bit of an issue with the charge/discharge sliders getting set to an initial value upon startup (or restart of HA). The SHP does not appear to report those readings except when they change. My workaround for the YAML package was an automation that would post that information to a separate ../status topic with a retained flag and then source the state for those sliders from there...

```
  - id: 'EF_SHP_Limits'
    alias: SHP - Limits
    description: 'Re-Publish SHP Charge/Discharge Limits to new Topic'
    mode: single
    trigger:
    - platform: mqtt
      topic: ecoflow/SHP/data
      payload: 30
      value_template: '{{ value_json.params[''id''] }}'
    condition: []
    action:
    - service: mqtt.publish
      data:
        topic: ecoflow/SHP/limits
        payload: '{{trigger.payload}}'
        retain: true
```

This "works" because I am using a local mosquito broker but it is not ideal and it not the proper approach for an integration. Perhaps we can discuss how best to address this. One possible solution is to initially send a request for 'latestQuotas' on ../get and then parse the ../get_reply to set initial values. This did not seem to be easily accomplished within a YAML package. Perhaps it is more easily done within an integration? I am new to coding for an integration so eager to both learn and contribute.

### CODE REVIEW

**Comment by Ne0-Hack3r** [comment]
Examples of calculated power sensors from my YAML package:
** wondering the best way to add these to the integration.
```
template:
  - sensor:
    - name: "SHP Grid Power"
      unique_id: shp_grid_power
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      state: >-
        {% if is_state('binary_sensor.shp_grid_available','on') %}
          {% set home = int(states('sensor.shp_all_ch_power')) %}
          {% set pro1 = int(states('sensor.shp_pro1_power'))   %}
          {% set pro2 = int(states('sensor.shp_pro2_power'))   %}
          {% if is_state('binary_sensor.shp_pro1_ac_charging','on') %}{% set pro1 = (pro1 * -1) %}{%endif%}
          {% if is_state('binary_sensor.shp_pro2_ac_charging','on') %}{% set pro2 = (pro2 * -1) %}{%endif%}
          {{ home - pro1 - pro2 }}
        {% else %}
          0
        {% endif %}

    - name: "SHP ALL PRO Output"
      unique_id: shp_all_pro_output
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      state: >-
        {{(int(states('sensor.shp_pro1_output'))+int(states('sensor.shp_pro2_output')))|round(0)}}

    - name: "SHP ALL PRO Charging Power"
      unique_id: shp_all_pro_charging_power
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      state: >-
        {{int(states('sensor.shp_pro1_charging_power'))+int(states('sensor.shp_pro2_charging_power'))}}

mqtt:
  sensor:
  - name: "SHP ALL Circuit Power"
    object_id: shp_all_ch_power
    unique_id: shp_all_ch_power
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state_topic: "ecoflow/SHP/data"
    qos: 0
    value_template: >-
      {% set l = value_json.params.infoList[:10] %}
      {% if l is defined %}{{l|sum(attribute='chWatt')|round(0)}}{%else%}{{this.state}}{%endif%}
```

Example Calculated Energy Sensors (riemann sum integration)
** Not sure how to add creation of these "helpers" to the integration or if there is a better approach.
```
sensor: 
- name: SHP Circuit 1 Energy
  unique_id: shp_ch1_energy
  source: sensor.shp_ch1_power
  round: 3
  platform: integration
  unit_prefix: k

- name: SHP Circuit 2 Energy
  unique_id: shp_ch2_energy
  source: sensor.shp_ch2_power
  round: 3
  platform: integration
  unit_prefix: k

  . . .
  
- name: SHP Grid Energy
  unique_id: shp_grid_energy
  source: sensor.shp_grid_power
  round: 3
  platform: integration
  unit_prefix: k
```

Example of energy sensors reported by SHP itself
```
  - name: SHP Grid kWh Today
    object_id: shp_grid_kwh
    unique_id: shp_grid_kwh
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total
    state_topic: "ecoflow/SHP/data"
    qos: 0
    value_template: >-
      {% set d = value_json.params['gridDayWatth'] %}
      {% if d is defined %}{{(d/1000)|round(2)}}{%else%}{{this.state}}{%endif%}
    
  - name: SHP Battery kWh Today
    object_id: shp_batt_kwh
    unique_id: shp_batt_kwh
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total
    state_topic: "ecoflow/SHP/data"
    qos: 0
    value_template: >-
      {% set d = value_json.params['backupDayWatth'] %}
      {% if d is defined %}{{(d/1000)|round(2)}}{%else%}{{this.state}}{%endif%}

  - name: SHP Circuit 1 Battery Energy
    object_id: shp_ch1_batt_energy
    unique_id: shp_ch1_batt_energy
    state_topic: "ecoflow/SHP/data"
    qos: 0
    device_class: energy
    unit_of_measurement: "Wh"
    state_class: total
    value_template: >-
      {% if value_json.params.id == 49 %}
        {% set d = value_json.params.watth[0] %}
        {% if d is defined %}
          {{d|sum|round(0)}}
        {%else%}{{this.state}}{%endif%}
      {%else%}{{this.state}}{%endif%}
    last_reset_value_template: >-
      {% if value_json.params.id == 49 %}
        {% set t = value_json.params.rtc %}
        {% if t is defined %}
          {{(as_timestamp(strptime(t,'%Y-%m-%d'))|as_datetime()).isoformat()}}
        {%else%}{{state_attr(this.state,'last_reset')}}{%endif%}
      {%else%}{{state_attr(this.state,'last_reset')}}{%endif%}

   . . . 
```
The above can be added as normal Energy Entities though, if we choose to add the battery energy per circuit, that may require some customization if we want to preserve the RTC timestamp reported by the SHP for those sensors.

**Comment by Ne0-Hack3r** [comment]
@tolwi - any interest in this or subsequent pull requests for Smart Home Panel?

**Comment by nickwinger** [comment]
Waiting for the SHP Integration :) will it be possible to switch the delta pros charging on/off ?

**Comment by parkee** [comment]
Any chance this is going to be merged soon? Any help is needed on this?
I really need the integration so I'll try to fork the repo and run it on my HA over the weekend.

**Comment by nickwinger** [comment]
FYI: I just managed to setup a MQTT SmartHomePanel Sensor in HomeAssistant with the official way.

Just Setup the MQTT Integration with the server (mqtt-e.ecoflow.com, port: 8883), certificateAccount etc. and then put this in your configuration.yml:

(This is an example of extracting the battery information from that quota json)
mqtt:
  sensor:
    - name: "SHP Battery"
      unique_id: "shp_battery"
      state_topic: "/open/open-<<your certificateAccount>>/<<SMART_HOME_PANEL_SN>>/quota"
      value_template: "{{ value_json.params.heartbeat.backupBatPer }}"
      device_class: null
      device:
        serial_number: <<SMART_HOME_PANEL_SN>>
        identifiers: <<SMART_HOME_PANEL_SN>>
        manufacturer: Ecoflow
        name: Smart Home Panel
        model: V1

**Comment by parkee** [comment]
Thank you so much. I'll check it out as well.
Honestly, all I really need is to be able to turn on/off EPS based on another sensor and charge batteries based on a sensor, schedule, and battery level.
The only issue I see is that you can't have more than 1 MQTT configuration, so I believe the bridge is needed since I already use MQTT locally.

**Comment by nickwinger** [comment]
@parkee I'm new to MQTT, but as far as i understood if you want to have more MQTT Server/Sources you would have to use the Mosquitto-Broker Add-On ?

**Comment by nickwinger** [comment]
@parkee  i just switched the EPS Mode on mine

If you have setup Ecoflow in the HomeAssistant MQTT Integration like i did, then you can try to publish in the Configuration Page:

Topic:
`/open/${certificateAccount}/${sn}/set`


PayLoad:
`{ "id": 123456789, "moduleType": 1, "operateType": "TCP", "version": "1.0", "sn": "SP10ZAW5ZE9E0052", "params": { "cmdSet": 11, "id": 24, "eps": 0 } }`

**Comment by parkee** [comment]
Yea, I guess so. I'm already using it since my energy meter shares the data via MQTT. I just need to read how to set up the bridge so I can integrate my Ecoflow SHP as well.

Thank you so much for your tips. I'm gonna play with it either this evening or this weekend. This PR also contains a lot of useful information on how to interact with the panel.

**Comment by parkee** [comment]
@nickwinger 
I'll have to wait a bit. I applied to get access to the dev portal, but it says I need to wait up to 5 working days. I've never seen anything like this before. Usually, API access is instant.
But since there's an official API now (I am not sure when it was introduced, but I'm pretty sure it didn't exist a year ago), I believe creating a completely new integration would make sense. Let's see if I can put enough effort into it.

**Comment by Nid01** [comment]
> @nickwinger I'll have to wait a bit. I applied to get access to the dev portal, but it says I need to wait up to 5 working days. I've never seen anything like this before. Usually, API access is instant. But since there's an official API now (I am not sure when it was introduced, but I'm pretty sure it didn't exist a year ago), I believe creating a completely new integration would make sense. Let's see if I can put enough effort into it.

@Mark-Hicks created the repository https://github.com/Mark-Hicks/ecoflow-api and already shared some progress on Facebook https://www.facebook.com/groups/1405868123482532/permalink/1628868904515785 and I am also working on my attempt in https://github.com/Nid01/EcoFlow-IoT-Open/tree/EcoFlow_IoT_Open.
When I'm focused enough in the next few days I should be able to implement the configuration of device parameters.

**Comment by nickwinger** [comment]
Yes, the official API is nice and beside the lack of good documentation and a way to get the certificate Account without having to run the java example it works very good. The only problem i see is as with the tuya stuff, being forced to go over the cloud having an internet connection instead of communicating with the device locally. In an emergency event, what the smart home panel was designed for, some may not have internet for some time.

**Comment by Mark-Hicks** [comment]
> Yes, the official API is nice and beside the lack of good documentation and a way to get the certificate Account without having to run the java example it works very good. The only problem i see is as with the tuya stuff, being forced to go over the cloud having an internet connection instead of communicating with the device locally. In an emergency event, what the smart home panel was designed for, some may not have internet for some time.

Example code is here:
https://github.com/Mark-Hicks/ecoflow-api-examples

All Ecoflow devices that use the app can connect using Bluetooth or ad hoc WiFi and SHP will function as configured in an outage. That doesn't necessarily help in terms our own integrations depending on the Ecoflow cloud API server but, unfortunately, Ecoflow has never shown any interest in creating a local TCP/BLE base API.

**Comment by notafishtoday** [comment]
Is there guidance around what approach is best for the SHP now? I used @Ne0-Hack3r's https://github.com/Ne0-Hack3r/hassio-ecoflow-cloud and made changes to use `schedule_update_ha_state`. This seems to work well for most things. Unfortunately it's throwing an error when I try to switch an individual circuit to battery: 
```
While executing automation automation.switch_to_battery_when_weather_is_good
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 723, in async_trigger
    return await self.action_script.async_run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1769, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 663, in _service_handler
    response = await self._async_start_run(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 621, in _async_start_run
    script_result = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 652, in _async_run
    return await self.script.async_run(script_vars, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1769, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 780, in _async_device_step
    await device_action.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/action.py", line 72, in async_call_action_from_config
    await platform.async_call_action_from_config(hass, config, variables, context)
  File "/usr/src/homeassistant/homeassistant/components/select/device_action.py", line 122, in async_call_action_from_config
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 191, in async_handle_select_option
    await self.async_select_option(option)
  File "/config/custom_components/ecoflow_cloud/select.py", line 45, in async_select_option
    self.send_set_message(val, self.command_dict(val))
  File "/config/custom_components/ecoflow_cloud/entities/__init__.py", line 76, in send_set_message
    super().send_set_message({self.__adopted_mqtt_key(): target_value}, command)
  File "/config/custom_components/ecoflow_cloud/entities/__init__.py", line 33, in send_set_message
    self._client.send_set_message(target_dict, command)
  File "/config/custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py", line 345, in send_set_message
    self.data.update_to_target_state(mqtt_state)
  File "/config/custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py", line 150, in update_to_target_state
    self.__broadcast()
  File "/config/custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py", line 164, in __broadcast
    self.__params_observable.on_next(self.params)
  File "/usr/local/lib/python3.12/site-packages/reactivex/subject/subject.py", line 59, in on_next
    super().on_next(value)
  File "/usr/local/lib/python3.12/site-packages/reactivex/observer/observer.py", line 39, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.12/site-packages/reactivex/subject/subject.py", line 66, in _on_next_core
    observer.on_next(value)
  File "/usr/local/lib/python3.12/site-packages/reactivex/observer/autodetachobserver.py", line 28, in on_next
    self._on_next(value)
  File "/config/custom_components/ecoflow_cloud/entities/__init__.py", line 101, in _updated
    if self._update_value(values[0].value):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/devices/smart_home_panel.py", line 33, in _update_value
    return super()._update_value({"sta": val['ctrlSta'], "ctrlMode": val['ctrlMode']})
                                         ~~~^^^^^^^^^^^
KeyError: 'ctrlSta'
```

**Comment by Ne0-Hack3r** [comment]
@notafishtoday 

I'm not pursuing this any longer in terms of updating the ecoflow-cloud integration for SHP. If you want to design your own or just use a custom YAML package, I can invite you to my private repo for a kick start on that (but I have to plans to take that any further either at this point).

You may also want to check out the official open API supported by Ecoflow:
https://developer.ecoflow.com/

**Comment by Ne0-Hack3r** [comment]
Having had no response or feedback from the author, I'm closing this pull request.

**Comment by notafishtoday** [comment]
@Ne0-Hack3r if you wouldn't mind inviting me to your repo I'd really appreciate it. Thanks!

**Comment by Ne0-Hack3r** [comment]
> notafishtoday

Done

**Pull request closed without merging**
